spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session失效时间
  session:
    timeout: 86400
    store-type: redis
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://106.54.5.213:3306/huoban'
    username: root
    password: 951753
  # redis配置
  redis:
    port: 6379
    host: localhost
    database: 0
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain:
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

